travis-build.sh
forgot that the local build and Travis build are using different scripts
=> fixed travis build following removal of GitVersion.cpp

src/core/datatypes/trees/Tree.cpp, src/core/datatypes/trees/Tree.h, src/revlanguage/datatypes/phylogenetics/trees/RlTree.cpp
Created a little function to get node indices from trees in the rev language.
=> Added a method getIndices to trees to get the node indices as a vector.

src/core/datatypes/phylogenetics/Taxon.cpp, src/core/datatypes/phylogenetics/characterdata/AbstractCharacterData.cpp, src/core/datatypes/phylogenetics/characterdata/DiscreteTaxonData.h, src/revlanguage/monitors/Mntr_Model.cpp
I need to merge the changes I made to the JSON formatter for the data so we can continue to work on the GUI.
=> Fixed JSON formatting problems. Validated JSON string.

src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractHomologousDiscreteCharacterData.cpp
=> function for breaking up a matrix by state size

help/md2help.pl, src/core/help/RbHelpDatabase.cpp
This change does 2 things:
* it replaces tabs with 8 spaces
* it finds the smallest number of leading spaces for non-empty lines, and removes that number of spaces from each line.
=> Allow indentation in the help examples.

src/core/functions/math/AbsoluteValueFunction.h
This is a demo for new developers, demonstrating the nifty new workflow pattern (branches with pull requests).
=> Fixed a typo as part of a demo for the RevBayes workflow practice.

src/core/datatypes/math/MatrixBoolean.cpp, src/core/datatypes/math/MatrixBoolean.h, src/core/datatypes/phylogenetics/AverageDistanceMatrix.cpp, src/core/datatypes/phylogenetics/AverageDistanceMatrix.h, src/core/datatypes/phylogenetics/DistanceMatrix.cpp, src/core/datatypes/phylogenetics/DistanceMatrix.h, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_Ordered.cpp, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_Ordered.h, src/core/functions/phylogenetics/ratematrix/OrderedRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/OrderedRateMatrixFunction.h
Added doxygen documentation for OrderedRateMatrixFunction, RateMatrix_Ordered, DistanceMatrix, AverageDistanceMatrix, and MatrixBoolean.
=> Doxygen for rate & distance matrices

src/core/distributions/phylogenetics/tree/coalescent/demography/ConstantDemographicFunction.cpp, src/core/distributions/phylogenetics/tree/coalescent/demography/ConstantDemographicFunction.h, src/core/distributions/phylogenetics/tree/coalescent/demography/DemographicFunction.cpp, src/core/distributions/phylogenetics/tree/coalescent/demography/DemographicFunction.h, src/core/distributions/phylogenetics/tree/coalescent/demography/ExponentialDemographicFunction.cpp, src/core/distributions/phylogenetics/tree/coalescent/demography/ExponentialDemographicFunction.h, src/core/distributions/phylogenetics/tree/coalescent/demography/LinearDemographicFunction.cpp, src/core/distributions/phylogenetics/tree/coalescent/demography/LinearDemographicFunction.h
Added doxygen comments, deleted commented-out code, changed a few comments within the code.
Checking correctness of the doxygen descriptions would be good.
In ExponentialDemographicFunction.cpp and LinearDemographicFunction.cpp one condition was used twice in the if clauses, I added a "@todo" there, so that these conditions can be either deleted or adjusted if they should be a different condition.
=> Modified the demography functions

validation/scripts/Validation_Binomial.Rev
Hello - This is my first PR to revbayes/revbayes for the hackathon
The test is mostly copied from the other tests. I chose n = 7 trials at random
Cheers
Bjørn
=> Adding validation test for binomial distribution

README.md
=> Add link to old repo in readme

src/core/distributions/phylogenetics/tree/coalescent/demography/ExponentialDemographicFunction.cpp, src/core/distributions/phylogenetics/tree/coalescent/demography/LinearDemographicFunction.cpp
Removed the duplicated condition in the if statements. Also removed the corresponding "@todo" in the doxygen documentation.
=> removed the duplicated check in the demographic functions

help/md/stochasticMatrix.md, src/core/functions/math/StochasticMatrixFunction.cpp, src/core/functions/math/StochasticMatrixFunction.h, src/revlanguage/datatypes/math/RlStochasticMatrix.cpp, src/revlanguage/datatypes/math/RlStochasticMatrix.h, src/revlanguage/functions/math/Func_stochasticMatrix.cpp, src/revlanguage/functions/math/Func_stochasticMatrix.h, src/revlanguage/workspace/RbRegister_Func.cpp, src/revlanguage/workspace/RbRegister_VectorType.cpp
- created RlStochasticMatrix datatype for row-stochastic matrices (each row is a simplex).
- created StochasticMatrixFunction to build core MatrixReals from a vector of simplices.
- created Func_stochasticMatrix to expose StochasticMatrixFunction to revlanguage, returns a RlStochasticMatrix.
- wrote a help file for Func_stochasticMatrix
=> Stochastic matrix

src/revlanguage/functions/math/Func_meanSimplex.cpp, src/revlanguage/functions/math/Func_meanSimplex.h, src/revlanguage/functions/math/Func_sumSimplex.cpp, src/revlanguage/functions/math/Func_sumSimplex.h, src/revlanguage/workspace/RbRegister_Func.cpp
=> Define simplex mean and sum functions

projects/meson/README.md
=> Fix meson install instructions.

src/core/io/NclReader.cpp, src/revlanguage/moves/tree/Move_LayeredScaleProposal.cpp
=> Removed debug output

.github/workflows/build.yml
Will send a notification to the #github channel (one notification per commit)
=> Notify Slack on result of github-actions

NEWS.md
to make releases easier and provide a record of improvements made
=> Added changelog

.github/workflows/build.yml
Temporary workaround (see issue https://github.com/actions/virtual-environments/issues/1811)
=> Fixed mac build on github actions

.github/workflows/build.yml, meson.build, src/core/datatypes/phylogenetics/character/CharacterTranslator.cpp, src/core/datatypes/phylogenetics/character/CharacterTranslator.h, src/core/datatypes/phylogenetics/character/DnaState.cpp, src/core/datatypes/phylogenetics/character/DnaState.h, src/core/datatypes/phylogenetics/character/DoubletState.cpp, src/core/datatypes/phylogenetics/character/DoubletState.h, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_GTR.cpp, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h, src/revlanguage/distributions/phylogenetics/character/Dist_phyloCTMC.cpp
Initial stab at a doublet alphabet 
[mcmc_GTR.Rev.txt](https://github.com/revbayes/revbayes/files/5707272/mcmc_GTR.Rev.txt)
=> Add a Doublet alphabet

.github/workflows/build.yml, projects/meson/make_winroot.sh
Updates the boost version for windows build
Adds workaround for Mac issue listed here https://github.com/actions/virtual-environments/issues/2322
=> Fix automated builds

src/core/functions/vector/VectorIndexOperator.h, src/revlanguage/datatypes/math/RlSimplex.cpp, src/revlanguage/functions/internal/Func__simplexIndexOperator.cpp, src/revlanguage/functions/internal/Func__simplexIndexOperator.h, src/revlanguage/workspace/RbRegister_Basic.cpp, src/revlanguage/workspace/RbRegister_BasicType.cpp
Basically I added a call to the internal vector index function so that [] can be used within deterministic nodes.
=> Fixing bug described in https://github.com/revbayes/revbayes/issues/133

projects/singularity/Singularity, projects/singularity/release.cmd
Maybe a GitHub action to test the singularity build is in order...
=> adding Singularity recipe

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCClado.h
Factor out code that modifies or scans the data matrix into separate functions.
Previously, three of these functions were in a single loop, which could result in some of the modification stopping on the first ambiguous character.
=> Fix weird ambiguous char issue

src/core/math/RbMathFunctions.cpp
Fixing a small error I missed in #150.
=> small fix to incomplete gamma function

NEWS.md
Adding items to NEWS.md about bug fixes and changes made to the AverageDistanceMatrix class
=> Add news item about AverageDistanceMatrix

projects/meson/generate_sources.sh, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_revPoMoThree4N.cpp, src/core/io/CountFileToNaturalNumbersConverter.cpp, src/core/io/DelimitedDataReader.cpp, src/core/io/FastaFileToNaturalNumbersConverter.cpp, src/core/utils/StringUtilities.cpp, src/libs/ncl/nxsstring.h, src/revlanguage/distributions/phylogenetics/tree/Dist_CharacterDependentBirthDeathProcess.cpp, src/revlanguage/distributions/phylogenetics/tree/Dist_TimeVaryingStateDependentSpeciationExtinctionProcess.cpp
A few different fixes that reduce compiler warnings.
=> Misc fixes 1

projects/cmake/build.sh, src/CMakeLists.txt
Try to pass boost options in environment variables.
This is an alternative attempt to fix the bugs found in #234
=> Minimal changes to fix boost paths

src/core/distributions/phylogenetics/AbstractFossilizedBirthDeathRangeProcess.cpp, src/revlanguage/workspace/RbRegister_Dist.cpp
- Fixes a small issue when initializing time intervals in FBD ranges models
- Registers the generic FBDP distribution (an alias to BDSTP)
=> Two FBD fixes

.github/workflows/build.yml, src/core/analysis/MonteCarloAnalysis.cpp
Re-enable MPI test and fix an MPI compile error.
=> Re-enable MPI test and fix an MPI compile error

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCClado.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousConditional.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousDollo.cpp, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousDollo.h, src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousNucleotide.h, src/core/distributions/phylogenetics/tree/UniformTopologyBranchLengthDistribution.cpp, src/core/functions/phylogenetics/TreeAssemblyFunction.cpp, src/core/functions/phylogenetics/TreeAssemblyFunction.h, src/revlanguage/datatypes/phylogenetics/trees/RlTree.cpp
Some speed fixes from the dev_jsigao branch.
=> Fixes2 from dev jsigao

src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractDiscreteTaxonData.cpp
=> Fix dat_mol[1].nchar() when dat_mol is an alignment

NEWS.md, meson.build, src/revlanguage/utils/RbVersion.cpp
This PR updates the NEWS and bumps the version number for 1.2.1.
=> Release 1.2.1

.github/workflows/build.yml, .github/workflows/release.yml, meson.build, meson_options.txt, projects/cmake/build.sh, projects/meson/README.md, projects/meson/build.sh, src/CMakeLists.txt, src/revlanguage/main.cpp, src/revlanguage/ui/RevClient.cpp, src/revlanguage/ui/RevClient.h, src/revlanguage/utils/TerminalFormatter.cpp, src/revlanguage/utils/TerminalFormatter.h
This allows using jupyter notebooks with the standard rb executable.
=> Select jupyter with --jupyter command-line flag.

projects/meson/make_winroot.sh, src/core/datatypes/math/MatrixReal.cpp, src/core/datatypes/math/MatrixReal.h, src/revlanguage/workspace/RbRegister_Basic.cpp
Fixes #307 
A full fix might also require a way to create a MatrixRealSymmetric.
=> Add addition, subtraction, and negation for matrices.

.github/workflows/build.yml, src/revlanguage/dag/RlStochasticNode.h
This makes the .probability() member function work again.
I've tacked on a change that fixes some caching in the github actions tests.  I don't think you need to look at that.
=> Make the .probability() member function work again.

src/core/distributions/phylogenetics/AbstractFossilizedBirthDeathRangeProcess.cpp, src/core/distributions/phylogenetics/AbstractFossilizedBirthDeathRangeProcess.h, src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.cpp, src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.h, src/core/distributions/phylogenetics/tree/birthdeath/EpisodicBirthDeathProcess.h, src/core/distributions/phylogenetics/tree/birthdeath/FossilizedBirthDeathSpeciationProcess.cpp, src/core/distributions/phylogenetics/tree/birthdeath/FossilizedBirthDeathSpeciationProcess.h
The FBDSP (and maybe other distributions) didn't work because the function 'prepareProbComputation' wasn't overloaded correctly. The virtual function was constant but the overwriting function wasn't. Thus this new function was never called. This should be fixed. Not sure if that fixes all dnFBDSP issues.
=> Fixing issue FBDSP

src/core/functions/vector/VectorFlattenFunction.cpp
A simple change to fix issue #387.
=> Fix vectorFlatten()

src/core/datatypes/trees/Tree.cpp
The check for bad indices was off by one.
=> Fix crash reading trees with bad indices.

.github/ISSUE_TEMPLATE/bug_report.md
People keep on providing just one line of a failing script, see #405.  So then we begin most PRs by responding "please send us a complete script with data files so that I can run it".
=> Request a script and data files in the issue template.

src/core/utils/RbException.cpp, src/core/utils/RbException.h, src/revlanguage/datatypes/basic/Probability.cpp, src/revlanguage/datatypes/basic/Probability.h, src/revlanguage/datatypes/basic/RealPos.cpp, tests/test_basics/scripts/probability.Rev
An alternative approach to fixing `Probability(-1)` and `Probability(2)`.
Not very generalized.
=> Alternate probability fix

.github/workflows/release.yml, NEWS.md, meson.build, src/revlanguage/utils/RbVersion.cpp
This is a PR for releasing 1.2.3
The plan is to release immediately, and then release 1.2.4 around May 5-8.
=> Release 1.2.3

.github/workflows/build.yml, .github/workflows/release.yml, NEWS.md, meson.build, src/core/help/RbHelpDatabase.cpp, src/revlanguage/utils/RbVersion.cpp
Please approve but do not merge yet.
=> Release 1.2.4

src/core/functions/phylogenetics/TreeAssemblyFunction.h, src/core/math/RbMathLogic.cpp, src/revlanguage/functions/basic/Func_type.cpp
Correctly initialize a boolean variable that determines whether we set the initial branch lengths in TreeAssemblyFunction.
=> Fix branch length NaN

src/core/analysis/mcmc/Mcmcmc.cpp, src/core/analysis/mcmc/Mcmcmc.h
This PR should fix issue #521 by making sure MC^3 counts attempted and accepted moves correctly. If the problem is more fundamental than just bad counting, then this should at least make it easier to diagnose it.
=> Correct operatorSummary for MC^3 when moves are tuned

projects/meson/make_winroot.sh
we should probably try to make that less fragile at some point
=> Updated package version in Windows automated actions

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h
This PR adds some checks that some invariants assumed in the likelihood calculator are actually true.
Currently the invariants are:
1. If a tree node is dirty, then its parent is dirty.
2. If a tree node has a dirty p-matrix, the it has a dirty conditional likelihood.
Actually, for the second one, I am wondering if it is actually the parent node that should be required to be dirty.
=> Check some invariants for AbstractPhyloCTMCSiteHomogeneous

src/core/analysis/mcmc/Mcmcmc.cpp
=> MCMCMC checkpointing fix

src/core/moves/MetropolisHastingsMove.cpp, src/core/moves/SliceSamplingMove.cpp, src/core/utils/RbSettings.cpp, src/core/utils/RbSettings.h
For issues #565 and #567 we need to solve problems where PDFs for some distributions are out of date.  Right now this can be partially addressed by compiling with `-DDEBUG_MCMC`, but even that doesn't find all the problems.
This PR tries to make these problems slightly easier for users to look for by (i) changing the compile-time option to a run-time setting and (ii) adding some functionality to the slice sampler to say WHICH variable has an incorrect PDF seems to be incorrect.  It also simplifies the code for `performMcmcMove( )` _a lot_.  The `debugMCMC` setting is an integer level, with `0` having no effect, and higher levels enabling more costly functionality.
For #567, we can now get the following: 
```
$ rb-debug-O --setOption debugMCMC=1 script.Rev
RevBayes version (1.2.5-preview) …
```
=> Convert some MCMC checks from #ifdef to options.

help/md/time.md
This PR explains the effect of each parameter to `time()`.
(I'm guessing `fromBeginning` because it's currently broken – #571)
=> Document time

src/revlanguage/functions/math/Func_cos.cpp, src/revlanguage/functions/math/Func_cos.h, src/revlanguage/workspace/RbRegister_Func.cpp
This just adds a cosine function.
=> Add cosine function

help/md/exp.md, help/md/fnF81.md, help/md/fnGTR.md, help/md/fnHKY.md, help/md/fnK80.md, help/md/fnK81.md, help/md/fnT92.md, help/md/fnTrN.md, src/core/help/RbHelpDatabase.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_Kimura81.cpp
Added title, description and example to `help/md/exp.md`. Function is simple enough that no further details are needed, and I was not sure who the author was to add to authors field. Also ran `./build.sh -help2yml true` to regenerate `src/core/help/RbHelpDatabase.cpp`. Once merged, will add `help.yml` file to the website `_data` directory to change the documentation there.
=> Filled out help file for exp function.

help/md/fnF81.md, help/md/fnGTR.md, help/md/fnHKY.md, help/md/fnK80.md, help/md/fnK81.md, help/md/fnT92.md, help/md/fnTrN.md, src/core/help/RbHelpDatabase.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_Kimura81.cpp
Revert accidentally committed-by-unreview patch
=> Revert accidentally committed-by-unreview patch

help/md/fnF81.md, help/md/fnGTR.md, help/md/fnHKY.md, help/md/fnK80.md, help/md/fnK81.md, help/md/fnT92.md, help/md/fnTrN.md, src/core/help/RbHelpDatabase.cpp
Corrected previously accidentally pushed changes to rate matrix models. All should now have citations, examples, details on their parameters, and a description of the rate matrix elements.
=> Changes to rate matrix model help files

help/md/dnBernoulli.md, help/md/dnBeta.md, help/md/dnBimodalLognormal.md, help/md/dnBimodalNormal.md, help/md/dnBinomial.md, help/md/dnCategorical.md, help/md/dnCauchy.md, help/md/dnChisq.md, help/md/dnDirichlet.md, help/md/dnExponential.md, help/md/dnGamma.md, src/core/help/RbHelpDatabase.cpp, src/revlanguage/distributions/math/Dist_bimodalLnorm.cpp
Added more details and standardized help files for a number of stats distributions. Will continue later, stopped at `dnGamma`.
=> Completing and standardizing stats distributions help files, part 1

help/md/fnJC.md, help/md/stdev.md
=> add help for jukes cantor

src/core/analysis/MonteCarloAnalysis.cpp
This PR implements feature request #672, i.e., it displays the current values of stopping rule convergence statistics upon resuming an analysis from a checkpoint:
```
Appending to previous MCMC simulation of 1000 iterations
This simulation runs 4 independent replicates.
The simulator uses 1 different moves in a random move schedule with 1 moves per iteration
Stopping rules:
Target value for effective sample size (ESS): > 50
Target value for the Gelman-Rubin statistic (PSRF): < 1.01
Current values:    
Minimum effective sample size (ESS): 9.636138
Maximum value of the Gelman-Rubin statistic (PSRF): 1.013099
```
Note that to make this visually pleasing, I had to change the order in which certain operations are performed within `MonteCarloAnalysis::run`: we now reset the stopping rules …
=> Display current stopping rule values when resuming from a checkpoint

NEWS.md
maybe this one won't get stuck.
=> Testing123

src/core/analysis/MonteCarloAnalysis.cpp
A tiny fix that should solve #762.
=> Fix segfault in MPI + MC^3
