src/core/distributions/math/LognormalDistribution.cpp, src/core/distributions/math/LognormalDistribution.h, src/core/distributions/math/LognormalWithOffsetDistribution.cpp, src/core/distributions/math/LognormalWithOffsetDistribution.h, src/core/distributions/math/NegativeBinomialDistribution.cpp, src/core/distributions/math/NormalDistribution.h, src/core/functions/phylogenetics/ratematrix/HkyRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/HkyRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/JcRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/JcRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/K80RateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/K80RateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/Kimura81RateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/Kimura81RateMatrixFunction.h
Added documentation for Lognormal, LognormalWithOffset distributions; JC, K80, Kimura81, and HKY rate matrix functions. Since the branch is based off of doxygen, I figured pull requesting here would be a better idea.
=> Documentation for math distributions, nucleotide rate matrix functions

src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TIM.cpp, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TIM.h, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TVM.cpp, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TVM.h, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TamuraNei.cpp, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_TamuraNei.h, src/core/functions/phylogenetics/ratematrix/F81RateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/F81RateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/FreeSymmetricRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/FreeSymmetricRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/GtrRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/GtrRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/HkyRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/K80RateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/Kimura81RateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/T92RateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/T92RateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/TamuraNeiRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/TamuraNeiRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/TimRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/TimRateMatrixFunction.h, src/core/functions/phylogenetics/ratematrix/TvmRateMatrixFunction.cpp, src/core/functions/phylogenetics/ratematrix/TvmRateMatrixFunction.h
Added doxygen documentation to the functions creating rate matrices for the following models: F81, free symmetric, GTR, TN92, Tamura-Nei, Tim, Tvm.
=> Doxygen documentation for rate matrix functions

.github/workflows/build.yml
Since we have the computing power available, lets test older compilers.
The really interesting ones are probably 4.9 and maybe 4.8, which are installed on clusters, but for those I think I need to build boost with the old ABI.  This is the first step.
=> Test gcc-5, gcc-6 and gcc-7

src/core/datatypes/phylogenetics/ratematrix/RateMatrix_FreeK.cpp
Enforce that row probabilities of exp(Q) sum to 1.0 for RateMatrix_FreeK.
This is mostly important for unrealistically large branch lengths.  If the row probabilities for these weird branch lengths sum to 3, then we will get very favorable likelihoods for them, and not reject them.  So, this basically prevents inaccurate matrix exponentials from breaking MCMC.
This seems to be necessary for covarion models with a lot of states.  I think this is kind of orthogonal from making the exponential more accurate, since even more accurate versions can get weird results if the branch length is large enough.
=> Stabilize matrix exponential for RateMatrix_FreeK

.github/workflows/build.yml
This requires building boost with gcc-4.9, in order to get a boost with the right ABI that is also new enough.
=> Also test with gcc-4.9

projects/cmake/build.sh, projects/cmake/regenerate.sh
This removes arguments that start with `-D` from the current argument handling, and passes them to  cmake.  It also prints how and where cmake is called.
Passing args to cmake allows doing things like 
* `./build.sh -DBoost_DEBUG=ON`
* `./build.sh -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang`
and many other things.  We then have the option of making future options to `./build.sh` be cmake options instead of options to generate different scripts.
=> Allow passing -Darg to cmake.

.github/workflows/build.yml
Fix issue that's currently affecting windows build
https://github.community/t5/GitHub-Actions/libpulse0-fails-to-fetch-with-apt-repo-broken/m-p/55386#M9537
=> Run apt update before installing stuff

projects/cmake/build.sh, src/CMakeLists.txt
This branch fixes the fact that when using `build.sh` with `-boost_root` or `-boost_lib`, any previous options got erased.
It also:
* uses BOOST_LIBRARYDIR instead of BOOST_LIBRARY, which is not correct according to the docs
* cleans up and removes the variables LOCAL_BOOST_ROOT/LOCAL_BOOST_LIBRARY
* adds more examples to `build.sh -h` to show passing cmake variables directly.
* clarifies BOOST diagnostic messages printed by cmake.
=> Fix boost location hints for cmake.

src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h
When using ambiguous characters, and also partitioning standard data by state number, a bug caused the likelihood calculation to sum over the max state number instead of the number of states per partition.
=> Fix likelihood calculation for discrete characters

src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractHomologousDiscreteCharacterData.cpp
Pursuant to #86, explain behavior of the `setNumStates*` methods so users aren't caught off-guard.
=> add user message to setNumStates*

src/revlanguage/datatypes/basic/Real.cpp
Following up on #96, conversion from `Real` to `IntegerPos` was allowed for values > 0. This fixes that.
=> Make sure value is >= 1 when converting Real to IntegerPos

.github/workflows/build.yml
set-env is deprecated and will be removed eventually (see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
=> removing deprecated set-env

src/core/datatypes/phylogenetics/ratematrix/AbstractRateMatrix.cpp, src/core/datatypes/phylogenetics/ratematrix/AbstractRateMatrix.h, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_DECRateMatrix.cpp, src/core/datatypes/phylogenetics/ratematrix/RateMatrix_DECRateMatrix.h
Some time recently the stochastic mapping code was changed to always use calculateTransitionProbabilities(). This was apparently not an issue for most rate matrices, but it caused stochastic mapping under DEC to segfault (invalid index access).
Context: DEC has an option to condition on survival (i.e. not entering the "null range") which is used when computing calculateTransitionProbabilities(). Using method for stochastic mapping causes the algorithm to fail, because the algorithm requires P(t)=exp(Qt) to work. Stochastic mapping under uniformization fails when using P that conditions on survival because P(t|survival) != exp(Qt).
To restore the original functionality, I added a virtual function for calculateTransitionProbabilitiesForStochasticMapping() that by default calls …
=> bug fix for segfault under DEC + stochastic mapping

projects/cmake/build.sh, src/CMakeLists.txt
I added an option to the build script to activate static linking of Boost in the main `CMakeLists.txt` file. This is for building the Mac release.
=> add option for linking static boost libraries

src/revlanguage/functions/argumentrules/ArgumentRule.cpp
I have done a minor rewrite of how arguments are converted. Specifically, instead of replacing the value of the original argument, we now create a new variable with the converted type if the function is only executed once.
Note, I did a minor clean-up where we mistakingly set the variable name to the argument name. This now cases a problem with the tests because the test_CBDP has a different header name for one column in the log file. No one had noticed this bug before. We should simply replace the current test result delta -> shift_rate.
=> fixing bug described in issue #101

src/revlanguage/distributions/math/Dist_binomial.cpp, src/revlanguage/distributions/math/Dist_multinomial.cpp, src/revlanguage/distributions/math/Dist_nbinomial.cpp, src/revlanguage/functions/DistributionFunctionRv.h
This solves issue #135 and brings the Rev syntax inline with R.
=> Rename rbinomial, rnbinomial and rmultinomial argument names to size

src/core/monitors/SiteMixtureAllocationMonitor.h
The SiteMixtureAllocation monitor was using the total number of characters, not the number of included characters, to report site matrix mixture allocations. This solves issue #147.
=> Use correct number of sites in mnSiteMixtureAllocation

src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h, src/core/distributions/phylogenetics/tree/MultispeciesCoalescentUniformPrior.cpp, src/core/functions/distribution/DiscretizeGammaFromBetaQuantilesFunction.cpp, src/core/functions/distribution/DiscretizeGammaFunction.cpp, src/core/math/RbMathFunctions.cpp, src/core/math/RbMathFunctions.h, src/core/math/RbStatisticsHelper.cpp, src/core/math/distributions/DistributionChisq.cpp, src/core/math/distributions/DistributionGamma.cpp, src/core/math/distributions/DistributionInverseGamma.cpp
The internal RevBayes function for the incomplete gamma integral was implemented using [this algorithm](https://people.sc.fsu.edu/~jburkardt/cpp_src/asa032/asa032.html) for the regularized lower incomplete gamma function. I've generalized the function so now you can choose whether it should be regularized, and whether to use the upper or lower limits of integration.
The previous function had an extra argument `scale` that determined the scale over which the function should be regularized.
I didn't see any need for this since it is always just &Gamma;(&alpha;). The only reason I can think this was included was for some small optimization from eliminating repeated calls to the gamma function, or simply for hidden testing purposes. I went ahead and removed it.
=> Generalize the incomplete gamma function

meson.build, src/CMakeLists.txt, src/cmd/RbGTKGui.cpp, src/core/io/NclReader.cpp, src/core/utils/RbFileManager.cpp, src/core/utils/RbSettings.cpp, src/core/utils/StringUtilities.cpp
_WIN32 is automatically defined by compilers when targeting the windows
ABI (either 32-bit or 64-bit).  Instead of defining our own flag, we should use that.
=> Check for _WIN32 instead of RB_WIN when checking for windows.

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h
There was a bug in mnSiteMixtureAllocation that transposed the site-specific allocations for site-rates and site matrices. I fixed it!
=> fixing a bug in mnSiteMixtureAllocation

src/core/moves/SliceSamplingMove.cpp, src/core/moves/SliceSamplingMove.h, src/revlanguage/moves/scalar/Move_SliceSampling.cpp, src/revlanguage/moves/scalar/Move_SliceSampling.h
Hi,
This updates slice sampling to use the "doubling" strategy instead of the "stepping out" strategy to find slice boundaries.
It also introduces a new argument to mvSlice to select between the two strategies -- by the new "doubling" strategy is used by default.
I have done some basic testing, and the "doubling" strategy can definitely speed up burnin, in cases where you want a large step size initially, but not generally.
-BenRI
=> Update slice sampling

src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h
Issue #131 is caused by intermediate `nan` values in the computation of partial likelihoods in `PhyloCTMCSiteHomogeneous.h`. This fixes that issue by allowing `nan`s to pass through the assertion.
=> Allow intermediate `nan` likelihoods in PhyloCTMC

.github/workflows/build.yml
GitHub actions stopped supporting Ubuntu 16.04 as a virtual environment on September 20, 2021.
So, this pull request disables the `ubuntu-16.04` integration test. I have also removed this check from the list of those required for merging into `development` and `master`.
See: https://github.com/actions/virtual-environments/issues/3287
=> Remove integration test for Ubuntu 16.04

src/core/moves/SliceSamplingMove.cpp, src/core/moves/SliceSamplingMove.h, src/revlanguage/moves/scalar/Move_SliceSampling.cpp
Fix two bugs in slice sampling:
- log_0 was defined incorrectly -- just use negative infinity
- rule out negative values when sampling RealPos variables.
I have some code to set the allowed values to the interval [min,max], but that is perhaps overkill.
=> Fix slice sampling

src/CMakeLists.txt
Switching cmake from v2 to v3 helps avoid some hacks in our CMakeLists.txt.
It also fixes some problems in finding BOOST.
I picked 3.5.1 (from 2016) because it was shipped with ubuntu 16.04. The most recent version is 3.22.
Most linux cluster should have a recent cmake available using i.e. `module add cmake`.
Based on the monthly meeting today, I think we have consensus on increasing the minimum version to v3.
=> Cmake increase min version to 3.5.1

meson.build, src/CMakeLists.txt
C++14 adds few features, and fixes some defects in C++11.
This patch doesn't actually doesn't change any code -- it just allows compiling C++14 code.
This patch is needed for a small code cleanup on a different branch.
=> Change the standard to c++14.

.github/workflows/build.yml, meson.build, src/CMakeLists.txt
I think that linux compiles already need to download and compile boost, with the version in the examples being 1.71
This PR bumps that to 1.71 and makes it a requirement.
The latest version is 1.77.
I don't think this would affect mac or windows.
=> Require Boost version 1.74

.github/workflows/build.yml, projects/meson/README.md, projects/meson/make_winroot.sh
This updates the `make_winroot.sh` script and allows building RevStudio again:
* We no longer need to generate a `pkg-config` wrapper with modern versions of meson.
* `c_args` and `cpp_args` should be in section [built-in options] now.
* give helpful error message if `zstd` cannot be found to decompress the packages
* adds an option to not download packages if you just want to regenerate win64-cross.txt
* avoid redownloading MINGW packages that have already been downloaded
* download packages MINGW packages for GTK if asked (needed for RevStudio)
* switch from `x86_64-w64-mingw32-gcc` to `x86_64-w64-mingw32-gcc-posix` to use POSIX threads (needed for RevStudio)
* general cleanups
=> Update make_winroot.sh, describe cross-builds in README.md, and fix RevStudio build

help/md/fnFMutSel.md, help/md/fnFMutSel0.md, help/md/fnMutSel.md, help/md/fnMutSelAA.md, help/md/fnX2.md, help/md/fnX3.md, help/md/fndNdS.md, src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h, src/core/functions/phylogenetics/ratematrix/CppCodonFuncs.cpp, src/core/help/RbHelpDatabase.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_FMutSel0RateMatrix.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_FMutSelRateMatrix.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_MutSelAARateMatrix.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_MutSelRateMatrix.cpp, src/revlanguage/functions/phylogenetics/ratematrix/Func_dNdSRateMatrix.cpp
This PR reorders arguments in the newly-introduced codon model functions to place submodels as the first argument.
This is necessary to allow the use of the R 4.1 pipe operator `|>` for easy substitution model composition, if and when the the pipe operator is added to revbayes.  However, we need to do this before the 1.2 release so that we don't break users scripts by changing the argument order later.
=> Codon model argument order

src/core/utils/RbFileManager.cpp, src/core/utils/RbFileManager.h, src/core/utils/RbSettings.cpp, src/core/utils/RbSettings.h
This fixes setwd(dir) on windows by using boost filesystem to set the current directory.  This means that we get to rely on boost filesystem to parse windows pathnames.  It also means that we no longer have to keep a string inside revbayes to track the current directory ourselves.
Incidentally, this means that `setwd("..")` now works.
We still handle `~`.
=> Fix windows setwd

.github/workflows/release.yml, doc/release-workflow.md, projects/singularity/Singularity
This PR is supposed to assist with the 1.2 release.
It autobuilds a linux singularity image, in addition to the standard compile.
It also adds an initial release workflow document-- although I can split that out if people prefer.
=> Build singularity image & add initial release workflow

src/core/analysis/mcmc/Mcmcmc.cpp, src/core/analysis/mcmc/Mcmcmc.h
This patch 
* cleans up the MC3 code
* adds mixing statistics that supplement the probability of swapping chains
* adds a comment and paper reference about the new mixing statistics.
There do not appear to be any MC3 tests in the testsuite, but I modified `test_JC_unrooted` (which is fast) to do the following:
```
mymcmc = mcmcmc(mymodel, monitors, moves, nchain=4, nruns=2, tuneHeat = TRUE)
mymcmc.burnin(generations=200,tuningInterval=20)
mymcmc.run(generations=2000)
```
According to my tests, there is no change to the output file `output{,4}/mcmcmc_JC_unrooted_uniform_run_1.out`.
=> Clean up MC3 code + add some MC3 mixing statistics

src/core/datatypes/trees/TopologyNode.cpp, src/core/datatypes/trees/TopologyNode.h, src/core/datatypes/trees/Tree.cpp, src/core/distributions/phylogenetics/tree/AbstractMultispeciesCoalescent.cpp, src/core/distributions/phylogenetics/tree/AbstractRootedTreeDistribution.cpp, src/core/distributions/phylogenetics/tree/DuplicationLossProcess.cpp, src/core/distributions/phylogenetics/tree/MultispeciesCoalescentMigration.cpp, src/core/distributions/phylogenetics/tree/UniformTimeTreeDistribution.cpp, src/core/distributions/phylogenetics/tree/birthdeath/ConditionedBirthDeathShiftProcessContinuous.cpp, src/core/distributions/phylogenetics/tree/birthdeath/HeterogeneousRateBirthDeath.cpp, src/core/distributions/phylogenetics/tree/birthdeath/StateDependentSpeciationExtinctionProcess.cpp, src/core/distributions/phylogenetics/tree/birthdeath/TimeVaryingStateDependentSpeciationExtinctionProcess.cpp, src/core/distributions/phylogenetics/tree/coalescent/AbstractCoalescent.cpp, src/revlanguage/functions/phylogenetics/tree/Func_simCompleteTree.cpp, src/revlanguage/functions/phylogenetics/tree/Func_simTree.cpp
Investigating #240, it seems that reading some trees with sampled ancestors does not work.
The problem seems to be that when calling `getRoot().makeBifurcating( as_fossils )`, new tip nodes are created.  All of these new nodes have index 0 because the index is never set.  Later, `orderNodesByIndex( )` crashes because multiple nodes have the same index.
The patch here does three things:
1. it distinguishes between an index of 0 and an index that has never been set.
2. it makes TopologyNode::getIndex( ) complain when the node index has never been set.
3. it changes make the call to `set_root( , )` always recompute node indices after the call to `getRoot().makeBifurcating( as fossils )`
Distinguishing between nodes with an unset index, and nodes with index 0 should help to prevent problems …
=> Don't crash when reading some trees

.github/workflows/build.yml
This PR removes GCC 6 from the list of test compilers, since github is going to start making it fail in October.
It also 
* adds a GCC-11 test to replace the GCC-6 one
* bumps the XCode test to XCode 12.4
* bumps the clang test to clang 11
=> Update test compilers1

src/core/distributions/phylogenetics/tree/birthdeath/SampledSpeciationBirthDeathProcess.cpp, src/core/functions/phylogenetics/cladogenetic/DECCladogeneticStateFunction.cpp, src/core/math/RandomNumberGenerator.h, src/core/moves/characterhistory/BiogeographyCladogeneticRejectionShiftProposal.h, src/core/moves/characterhistory/BiogeographyNodeRejectionSampleProposal.h, src/core/moves/characterhistory/BiogeographyNodeRejectionShiftProposal.h, src/revlanguage/parser/Parser.cpp, src/revlanguage/parser/Parser.h, src/revlanguage/parser/grammar.tab.cpp, src/revlanguage/parser/grammar.tab.h, src/revlanguage/parser/lex.yy.cpp
RevBayes won't compile out-of-the-box on current XCode,  This is because RevBayes uses some deprecated features in C++14 that are actually removed in C++17. XCode now defaults to C++17, and its libc++ implementation actually removes the deprecated features.  GCC also defaults to C++17. 
The removed features are mainly:
* use of the `register` keyword in the generated parser/lexer.
* use of `std::random_shuffle( )` in a few files.
With this PR, RevBayes continues to target C++14, but removes deprecated features so that it is possible to compile it in C++17 mode.
* the parser/lexer are regenerated using more modern flex/bison, and so don't use the `register` keyword
* a simple implementation of random_shuffle( ) is placed in namespace `deprecated`
* `std::random_shuffle( )` is replaced with …
=> Fix compatibility with C++17

src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.cpp, src/revlanguage/distributions/phylogenetics/tree/Dist_FBDP.cpp
This PR includes two simple fixes that address the following issues:
(1) While `dnBDSTP()` and its alias, `dnFBDP()`, currently accept an `initialTree` argument, they ignore it and proceed to simulate a starting tree regardless of whether a user-specified initial tree has been provided.
(2) While `dnBDSTP()` and `dnFBDP()` are indeed supposed to be aliases, their behavior differs when the `rho` argument (extant sampling fraction) is specified: the former accepts it, while the latter throws a seemingly unrelated error:
```
No parameter with name "rhoTimeline" found to set
```
Here, the code was changed to ensure that the `rho` argument is accepted by both aliases.
=> Accept constant rho and user-supplied starting trees in dnFBDP()

src/revlanguage/functions/UserFunction.cpp, src/revlanguage/parser/SyntaxIndexOperation.cpp, src/revlanguage/workspace/RevVariable.cpp, src/revlanguage/workspace/RevVariable.h
Currently, you can define functions in Rev.  For example:
```
function sampleDirichlet(n, alpha)
{
for(i in 1:n)
{
x[i] ~ dnGamma(alpha, 1.0)
}
return x/sum(x)
}
```
However, this function fails with the message:
```
> sampleDirichlet(10,2)
Missing Variable:	Variable x[1] does not exist
```
The reason is that
*  each function has its own Environment that maps names to objects.  In this case, the function Environment includes the names `n`, `alpha`, `x`, `x[1]`, `x[2]`, ... etc.
* when we create vectors like `x`, RevBayes does not immediately lookup and record the RevVariable for each of the elements of `x`.
Instead, RevBayes sets the flag `needs_building` and defers construction of the vector until getRevObject( ) is called for `x`.
* when building the vector, RevBayes needs to look up …
=> Fix vectors in functions2

src/core/datatypes/trees/TopologyNode.cpp
Apparently removing the cached value and recomputing the likelihood leads to a different likelihood!  That has to be a bug.
Only the BDSTP test is actually affected by this, so I updated on the BDSTP test results.
=> Correctness fix for node dirty flagging

src/core/utils/RbFileManager.cpp
This is necessary to avoid a crash when you run `model.graph("file.dot")`.  Otherwise it throws an exception trying to create a directory from an empty path.
=> Only try to create the parent directory if there is one.

src/core/datatypes/trees/Tree.cpp, src/core/moves/proposal/tree/NearestNeighborInterchange_nonClockProposal.cpp
This PR fixes `Segmentation fault` errors in NNI and SPR.  In both cases, a loop was created in getParent() edges, and this lead to an infinite loop in recursive-dirty-flagging which overflowed the stack.
The PR also adds an error message indicating that the NNI proposal does not (currently) handle a root node with only 2 children.
=> Fix constrained topo

src/revlanguage/functions/basic/Func_setwd.cpp, src/revlanguage/parser/Parser.cpp
Without the patch we get (for example):
```
> setwd("asdf")
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
what():  boost::filesystem::current_path: No such file or directory: "asdf"
Aborted
```
With the patch, we get
```
> setwd("asdf")
Error:	setwd: The path "asdf" does not exist.
```
The PR:
* checks if the filename exists and is a directory first, before we try and set it as the current directory.
* modifies the read-eval-print loop not to crash on exceptions that are not RbException, such as boost::filesystem::filesystem::error.
=> Don't crash in setwd(dir) if dir does not exist.

src/revlanguage/workspace/RevVariable.cpp, src/revlanguage/workspace/RevVariable.h
When reworking the `needs_building` functionality for vectors, I accidentally removed the line to set `needs_building = false` after building the vector.
This didn't break any of the existing tests, but made converting Natural[] to RealPos[] not work :grimacing: .
Fixed by remembering to set the flag.
=> Fix type conversion for vectors.

src/core/analysis/ValidationAnalysis.cpp
ValidationAnalysis::summarizeAll( ) broke when we switched from the `RbFileManager` class to `boost::filesystem::path`.
ValidationAnalysis::summarizeAll( ) was using std::stringstream to join paths.  This worked before, when filenames were just `std::string`.  However filenames are now streamed in double-quoted form, which led to `ValidationAnalysis::summarizeAll( )` to create filenames with double-quotes in the actual name, like `""output_Beta"/Validation_Sim_1/posterior_samples.var"`.
Fix this by using the "/" operator to join paths.
=> Fix validation analysis.

.github/workflows/release.yml, meson.build, src/CMakeLists.txt
This branch tries to fix problems reported by @rachelwarnock and @jembrown where executables don't "just work" on Mac.  Instead, you had to install boost and openlibm with homebrew.
To fix that, this branch:
- stops using openlibm for release builds (normal testing continues to us openlibm)
- compiles a static boost on linux and mac systems, and links to the static boost
- sets RPATH to look for shared libs first in `../lib/RevBayes/` relative to the position of the `rb` executable
- disables the `test_FBD/BDSTP.Rev` test.  This fails, presumably due to differences with and without openlibm.
To check that this fixes Rachel's problems, we need to check that the Mac executables are not dynamically linked to boost or openlibm.  You should be able to do this by 
* downloading the Mac …
=> Make released rb executables run on Mac without installing boost + openlibm

src/core/datatypes/phylogenetics/character/DiscreteCharacterState.cpp, src/core/datatypes/phylogenetics/character/DiscreteCharacterState.h, src/core/datatypes/phylogenetics/character/DnaState.cpp, src/core/datatypes/phylogenetics/character/DnaState.h, src/core/datatypes/phylogenetics/character/PoMoState.cpp, src/core/datatypes/phylogenetics/character/PoMoState.h, src/core/datatypes/phylogenetics/character/PoMoState4.cpp, src/core/datatypes/phylogenetics/character/PoMoState4.h, src/core/datatypes/phylogenetics/characterdata/DiscreteTaxonData.h
While looking for a problem in a someone's data set, I noticed that RevBayes was spending a lot of time copying and creating DNA characters in `readDiscreteCharacterData( )`.
One big culprit is that a `vector<double> weights` field was added to DiscreteCharacterState.  This is slow to copy because it requires a memory allocation for each character.  It also expands the memory footprint.  This field seems to have originally been part of PoMoState and PoMoState4, so I moved the field back to those classes.  Probably the idea needs a better design.
I did some testing, and this reduces the time to read a large DNA matrix from 6.2s to 1.4s -- about 4.5x faster.
It reduces the memory usages for that matrix from 3100M to 610M, about 5x smaller.
=> Improve speed and memory usage for DNA data by about 5x

meson.build, src/CMakeLists.txt
This PR switches to building with c++17.  It does not do anything else.
The major changes in c++17 are:
* new class std::optional.  Allows switching from boost::optional. (https://en.cppreference.com/w/cpp/utility/optional)
* new system std::filesystem. Allows switch from boost::filesystem. (https://en.cppreference.com/w/cpp/filesystem)
* structured bindings.  Allows _readable_ decomposition of pairs, tuples, etc.: (https://en.cppreference.com/w/cpp/language/structured_binding)
* `pair<int,double> [result1,result2] = function_that_returns_a_pair()`
* `for(auto& [key,value]: container_of_pairs) {...`
Other changes include
* new class std::variant -- a type safe union. (https://en.cppreference.com/w/cpp/utility/variant)
* new class std::any -- can hold any copy-constructible type. …
=> Change standard from c++14 to c++17.

src/revlanguage/parser/SyntaxFunctionCall.cpp, src/revlanguage/workspace/Environment.cpp, src/revlanguage/workspace/Environment.h, src/revlanguage/workspace/FunctionTable.cpp, src/revlanguage/workspace/FunctionTable.h
This is motivated by the common problem where people write `T <- readTrees("data/primates_tree.nex")`.  
Since the subscript `[1]` is missing, T is not a tree and so method calls like `T.taxa()` don't work.  This results in bug reports like #239.
This patch generates the "no method" error from `SyntaxFunctionCall::evaluateContent( )` instead of from `FunctionTable::findFunction( )`.  SyntaxFunctionCall has access to the type of the base variable, so we can add that to the error message.  We also suggest using `.methods()`.
```
> T = readTrees("primates.tree")
Attempting to read the contents of file "primates.tree"
Successfully read file
> T.ntips()
Error:	Variable of type 'TimeTree[]' has no method called 'ntips'.  You can use '.methods()' to find available methods.
```
This will …
=> Mention object type in error messages for missing method `object.method()`.

src/core/datatypes/trees/Clade.cpp, src/core/datatypes/trees/Clade.h, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp, src/core/utils/StartingTreeSimulator.cpp, src/core/utils/StringUtilities.cpp, src/core/utils/StringUtilities.h, src/revlanguage/datatypes/phylogenetics/trees/RlClade.cpp
Before simulating the constrained tree, we first sort clade constraints so that tip-ward clades are first.  However, this doesn't make sense for negated constraints, so we need to avoid checking for overlapping taxa between negated constraints and other constraints.
Another issue was that we said that there were conflicting constraints, but didn't say which ones.  So, print out the supposedly-conflicting constraints.  When regular constraints conflict, its because their taxon sets overlap, so also print out the overlapping taxa.
Another issue was that we printed out negated or "optional" constraints as if they were regular clade constraints.  So, print out `NOT A` for negative constraints and `(A OR B OR C)` for optional constraints. 
The underlying issue may be that the code for …
=> Fix false claim of conflicting constraints when simulating a constrained tree

src/core/datatypes/trees/Clade.cpp, src/core/datatypes/trees/Clade.h, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp
This is fixes problems reported in #162 and #250.  It is a followup to a previous PR #288 that partially fixed this problem, but not completely.
PR #288 used a partial order to sort the clades, which std::sort cannot handle.
Instead just sort the clades by the number of taxa they contain.  This should ensure that each clade comes before any other clade that includes it.  We still need to sort negative and optional constraints after real clades for this to work.
Since we aren't using cladeWithin anymore, we need to check for conflicting constraints separately.  Factor this out into a new function `checkConstraints(clades)`.  Also check that nested clades aren't older than clades that contain them.  Make sure to print out clades that supposedly conflict, so the user can tell why there are …
=> Fix constraints for real this time.

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h
Currently, during rescaling we divide by the largest conditional likelihood, and save its log for later use.  This prevents underflow of the conditional likelihoods.  But it doesn't help when the largest conditional likelihood is zero.
For example, if the conditional likelihoods for A, C, G, and T at a site are:
```
[ 1.0e-300, 1.0e-200, 1.0e-270, 1.0e-210]
```
then we would divide the conditional likelihoods by max = 1.0e-200 to get
```
[ 1.0e-100, 1.0, 1.0e-70, 1.0e-210]
```
Then we compute `log(max) = -460.517` and add it back in at the end of the likelihood calculation.
However, if we have 
```
[ 0.0, 0.0, 0.0, 0.0]
```
then dividing by the maximum is dividing by zero.  So we get:
```
[ NaN, NaN, NaN, NaN]
```
and we add in log(max) = NaN at the end :grimacing: .
So, just don't do …
=> Avoid NaN when rescaling

src/core/analysis/mcmc/Mcmc.cpp
Quote the node name and print the bad probability.  It helps to know if its zero or NaN.
=> Print clearer error message.

.github/workflows/build.yml, .github/workflows/release.yml
We are now supposed to write `echo "name=value" >> $GITHUB_OUTPUT`.
Since this is for the github actions scripts, and they seem to be passing, I would suggest that review should just be a quick glance over the code changes.
=> Fix deprecated `set-output::value` command in github actions.

.github/workflows/build.yml, .github/workflows/release.yml
Tests are failing because the ubuntu-latest image doesn't have gcc-7 and gcc-8.
This branch removes those checks (for gcc from 2017/2018) and adds a check for gcc-11 (for 2021).
=> Fix GHA tests - remove obsolete gcc-7 and gcc-8 checks

src/core/distributions/phylogenetics/tree/birthdeath/StateDependentSpeciationExtinctionProcess.cpp
It seems like a bug was introduced to CDBDP in our recent merge of dev_mrm into development. Specifically, the root-node likelihood calculations is attempting to use cladogenetic state-change events even when the model does not include them. 
I think the correct behavior should be that: if the root node is a speciation event AND the model includes cladogenetic state-change events, then we use the cladogenetic eventMap to combine probabilities at the root; if the root node is a speciation event and the model does NOT include cladogenetic state changes, then we multiply by the speciation rate in state i; if the root node is actually a sampled ancestor, we multiply by 1.0 (no event, since the "tip" corresponding to the sampled ancestor is initialized with density equal to the state-dependent …
=> fixing a problem with root-node probability calculations in CDBDP

src/core/analysis/mcmc/output/TreeSummary.cpp, src/core/analysis/mcmc/output/TreeSummary.h
RevBayes was crashing whenever we annotated a tree trace multiple times.  This was because it marked the individual runs "clean" after the first annotation.  Then, during the second annotation, it skipped computing the summary statistics (i.e. split frequencies) because all the individual runs were clean.
Solved by separately recording whether the summary statistics are computed yet.
In addition, this patch
1. Improves readability for TreeSummary.cpp
2. Makes mccTree substantially faster.
3. Renames splitFrequency to splitCount since it is an integer, and creates a new function splitFrequency that is a fraction.  Similar for topologyCount/topologyFrequency.
You could review this patch as one big change, but I recommend reviewing each of the 4 parts separately.  The readability patch is …
=> Fix multi summary

src/revlanguage/ui/RevClient.cpp
This fixes #292, where including `(` in a string resulting in a parse error if you were in interactive mode.
Apparently RevBayes registered a "character callback" in order to interrupt parsing and call 'printFunctionParameters' when it saw a '('.
I'm not quite sure why this broke parsing of `(` inside strings.  But this PR comments out the callback since
* the callback doesn't appear to actually do anything -- it doesn't print function parameters, for example
* removing the callback fixes the problem.
=> Fix open-parenthesis in a string in interactive mode.

src/core/datatypes/trees/Clade.cpp, src/core/datatypes/trees/Clade.h, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp, src/core/utils/StartingTreeSimulator.cpp
The following code crashed before:
> taxa <- simTree(8).taxa()
> simStartingTree(taxa, [ clade(taxa[1],taxa[2]) ])
The issue was that in the starting tree simulator we didn't check if optional constraints exist and used them either way. This should be fixed now.
=> fix missing check if optional constraints exist

src/core/analysis/mcmc/output/TreeSummary.cpp, src/core/analysis/mcmc/output/TreeSummary.h, src/core/datatypes/trees/TopologyNode.h, src/revlanguage/analysis/mcmc/output/RlTraceTree.cpp
This is a small addition to conveniently compute the posterior probability of a joint set of clades, i.e., the frequency in the tree sample how often all of the clades were found to be monophyletic. This helps to do some posthoc hypothesis testing.
=> Adding a member procedure to compute the joint probability of a set of clades

src/core/utils/RbSettings.cpp
Recent versions of RevBayes crashed because of corrupt .RevBayes.ini
This fixes it by writing the directory name as a string and not path.
=> Fixing the problem with .RevBayes.ini 

src/core/moves/compound/RateAgeBetaShift.cpp
We should not check for the likelihood shortcuts within a specific move but rather outside in the Metropolis-Hastings class. Here, the checks didn't even work anymore when node calibrations where used.
=> Removing likelihood shortcut check in RateAgeBetaShift move.

src/revlanguage/monitors/Mntr_HomeologPhase.cpp
A very minor fix for the homeolog phase monitor, which was breaking when trying to use the append argument.
=> minor fix to the homeolog monitor

src/core/datatypes/RbVectorImpl.h, src/core/distributions/events/MarkovEventsDistribution.h, src/revlanguage/distributions/RlTypedDistribution.h, src/revlanguage/distributions/phylogenetics/RlFossilizedBirthDeathRangeProcess.h, src/revlanguage/functions/RlTypedFunction.h
This also makes revbayes compile under C++20.
=> Constructors and destructors don't take template arguments.

projects/meson/make_winroot.sh
Update the version of openlibm to make the windows test pass.  The old version is no longer available.
=> Use more up-to-date-version of openlibm package on mingw.

src/core/distributions/phylogenetics/tree/birthdeath/GeneralizedLineageHeterogeneousBirthDeathSamplingProcess.cpp
The recent version had GitHub actions compile problems:
2023-07-03T10:43:00.1855320Z /Users/runner/work/revbayes/revbayes/src/core/distributions/phylogenetics/tree/birthdeath/GeneralizedLineageHeterogeneousBirthDeathSamplingProcess.cpp:1373:22: error: use of overloaded operator '==' is ambiguous (with operand types 'std::basic_string<char>::value_type *' (aka 'char *') and 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>'))
2023-07-03T10:43:00.1926980Z                                 if ( &var.back() == pattern )
This should hopefully fix it.
=> Compile error in GeneralizedLineageHeterogeneousBirthDeathSamplingProcess.cpp

src/core/datatypes/trees/Clade.cpp, src/core/functions/phylogenetics/FeatureInformedRateFunction.cpp
This is a very minor fix which adds <cmath> to make RevBayes compile properly again.
=> Fixing compile errors because of missing cmath include

src/core/datatypes/trees/Tree.cpp, src/core/datatypes/trees/Tree.h
Currently `Tree::getNumberOfInteriorNodes()` returns `-1` when a rooted tree has only 1 node.  When the `-1` gets converted to `size_t`, it turns into `2^64`.
Avoid this by not subtracting 1 when the root is also a tip (which occurs when the rooted tree has 1 node).
=> Don't return (2^64) when a rooted tree has 1 node.

src/core/datatypes/phylogenetics/characterdata/AbstractHomologousDiscreteCharacterData.cpp, src/core/datatypes/phylogenetics/characterdata/AbstractHomologousDiscreteCharacterData.h, src/core/datatypes/phylogenetics/characterdata/HomologousDiscreteCharacterData.h, src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractHomologousDiscreteCharacterData.cpp, tests/data/petromyzontiformes.nex, tests/test_discCharMethods/output_expected/Test_discCharMethods.txt, tests/test_discCharMethods/scripts/Test_discCharMethods.Rev
This branch makes the following changes to the class `AbstractHomologousDiscreteCharacterData`, originally suggested by Alessio Capobianco:
(1) Add a `.getInvariantSiteIndices()` method, which returns the indices of all characters that are invariant, either with or without accounting for ambiguities. The code is based on the pre-existing `.getNumInvariantSites()` method, which has been refactored to remove redundancies.
(2) Add a `.removeExcludedCharacters()` method, which entirely removes excluded characters from the matrix. The idea behind this method is to do for characters what we already do for taxa, where we have both an `.excludeTaxa()` method (which marks one or more taxa as excluded but keeps them in the matrix) and a `.removeTaxa()` method (which removes them entirely).
(3) Add …
=> Add and change AbstractHomologousDiscreteCharacterData methods

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp, src/core/distributions/phylogenetics/tree/birthdeath/ConstantRateOutgroupBirthDeathProcess.cpp, src/core/distributions/phylogenetics/tree/birthdeath/StateDependentSpeciationExtinctionProcess.cpp, src/core/distributions/phylogenetics/tree/birthdeath/TimeVaryingStateDependentSpeciationExtinctionProcess.cpp
This problem was caused by a change I made in the RbBitSet implementation a while back.
RbBitSet is now an alias to `boost::dynamic_bitset<>`.  So, RbBitSet(n, true) doesn't construct an all-1s bitset anymore.  Instead, the second argument is a `long int` that represents a bitmask.  So, passing in `true` initializes the bitset to `0000..001` 😬.
While fixing this problem, I noticed a few other cases where RbBitSet(n, true) occurred and fixed them too.
=> Fix problem reconstructing ancestral state with missing data.

src/core/datatypes/trees/Tree.cpp, src/core/help/RbHelpDatabase.cpp, tests/test_read_trees/scripts/read_trees.Rev
=> Handle the index for a node not being an integer (e.g. "index=NA")

.github/workflows/build.yml, projects/meson/make_winroot.sh
The windows build was broken because some of the old versions of libraries that we needed to build RevStudio went away.
Update the windows library packages that we download from mingw.
=> Fix windows build

src/revlanguage/functions/io/Func_readTreeTrace.cpp
This is intended to fix issue #412 and supplant PR #227 with a (hopefully) somewhat more elegant solution. The basic idea is still to prevent the user from creating 0-length traces in the first place, rather than to make sure that the class methods of `TraceTree` or summary functions like `mapTree()` can handle them. This is mostly done for the sake of brevity, and because I can't think of any use for a 0-length trace anyway.
@bredelings's idea of switching the order of argument types, so that `1` (or `1.0`) will get preferentially interpreted as an integer rather than a probability, was almost enough to solve the problem. The only other way to create a 0-length trace is to specify a burnin length that exactly matches the total number of trees in the trace, so I added an extra check that …
=> Make it impossible to create 0-length traces

src/core/distributions/ReversibleJumpMixtureConstantDistribution.h
Issue led to segmentation faults e.g. #429
=> Fixed memory leak in reversible jump mixtures

src/core/math/distributions/DistributionExponentialError.cpp
This branch provides a more efficient ln(pdf) calculation for the exponential error distribution, which is defined over distance matrices and underlies the (hopefully soon to be published) Bayesian Least-Squares Supertrees (BLeSS) method. Following Claudio Kozický's (@qak) suggestion, the new implementation reduces the number of `std::find` calls (from _n_(_n_ − 1)/2 to just _n_), yielding a roughly 36-fold speed-up for 5000-by-5000 matrices.
=> BLeSS efficiencies

projects/meson/make_winroot.sh
The tests were failing because of an outdated package version on windows.
After we merge this, other branches can include it to pass the tests.
=> Fix the github action tests on windows

src/core/math/distributions/DistributionExponentialError.cpp, src/core/math/distributions/DistributionExponentialError.h, src/core/utils/StringUtilities.cpp, src/core/utils/StringUtilities.h
Some additional improvements to the performance of ln(pdf), again following very helpful suggestions by Claudio Kozický ([@qak](https://github.com/qak)). The main changes are as follows:
(1) The "alignment" of the average distance matrix and the distance matrix of a proposed tree (i.e., the step of ensuring that we are subtracting distances corresponding to the same pair of taxa) is done using `std::sort` rather than `std::find`, which is up to two orders of magnitude faster for 10,000-by-10,000 matrices;
(2) Indexing is done using `uint32_t` rather than `size_t`, which speeds up memory access (and consequently, the matrix subtraction step).
In practice, the performance improvement gained by these changes can be difficult to observe, because the total amount of time spent on evaluating …
=> More BLeSS efficiencies

src/core/analysis/mcmc/Mcmc.cpp
This is another trivial, single-line bug fix that we've never gotten around to implementing, this time for issue #339. @jsigao suggested this as a solution and implemented it on [his branch](https://github.com/revbayes/revbayes/commit/ec20e7875f3f572c7ad55b0767b40c7492538b4c); I verified that it's sufficient to get rid of the issue. While the plan was to make it just one part of a more extensive checkpointing fix, it's been more than a year, and it seems worth fixing the issue even without a more general solution to MPI and MC^3 checkpointing problems. However, precisely because the problem of getting checkpointing to work under MPI is still [unresolved](https://github.com/revbayes/revbayes/issues/184), I'm holding off from adding a full-blown checkpointing test.
=> Don't flatten arrays of stochastic variables in checkpoint files

src/core/moves/proposal/scalar/ScaleProposal.cpp
This is a partial fix for the issue #272 where a bad interaction between tuning and mixture variable leads to overflow on the scaling factor used in mvScale
similar bounds are implemented in e.g. mvSlideBactrian
=> added bounds on tuning parameter for mvScale

src/core/utils/TreeUtilities.cpp
Apologies for implementing all of this in a piecemeal manner, but I just noticed the same trick I'd used in PR #432 to make `ExponentialError::lnPdf` more performant can also be exploited in `TreeUtilities::getAverageDistanceMatrix`. (In contrast, the even faster `std::sort`-based solution eventually implemented in PR #434 wouldn't work here, because we are working with string vectors of different lengths.) It results in an approximately 16-fold speed-up when computing 10,000-by-10,000 average distance matrices.
=> Compute average distance matrices more efficiently

src/core/datatypes/math/MatrixBoolean.cpp, src/core/datatypes/math/MatrixBoolean.h, src/core/math/distributions/DistributionExponentialError.cpp, src/core/utils/TreeUtilities.cpp, src/revlanguage/datatypes/math/RlMatrixBoolean.cpp, src/revlanguage/datatypes/phylogenetics/RlAverageDistanceMatrix.cpp, tests/test_avgDistMat/output_expected/Test_avgDistMat.txt, tests/test_avgDistMat/scripts/Test_avgDistMat.Rev
This PR is primarily intended to fix issue #468. Specifically, it makes the following three changes:
1. The type of the `rv` argument of one of the `executeMethod(...)` utility functions of class `MatrixBoolean` has been changed from `boost::dynamic_bitset<>` to `RbVector<Boolean>`.
2. The `.getElement()` method of class `AverageDistanceMatrix` returns a vector that no longer contains two doubles but rather a single string. This makes for nicer printing: instead of `[ 1.905, 1.000 ]`, we now get `[ 1.90471, TRUE ]`, which better indicates what's going on (i.e., each element of `AverageDistanceMatrix` is a numeric value associated with a Boolean that indicates whether or not this value should be used in further calculations).
3. A test (based on the script from #468) has been added to …
=> Improvements to MatrixBoolean and AverageDistanceMatrix

src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousConditional.h
There was previously an issue that mainly manifested itself when using posterior predictive simulations. The problem was that the site rate categories were not correctly drawn in the PhyloCTMC when it condition on variable coding. This is fixed now.
=> Fixing issue with simulation under ACRV and variable coding

src/revlanguage/RevLanguageMain.cpp
This is one way to set `args` equal to an empty `String[]` when no arguments are given.
=> Ensure that we can check `args.size()` even when no arguments are given.

src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.cpp
This PR restores the starting tree code in `BirthDeathSamplingTreatmentProcess.cpp`, which was introduced there in PR #386 to fix issue #354, but which was then (accidentally, it seems) removed in PR #399. As a result, it's once again possible to sample fossil ages from their respective priors even when a user-supplied starting tree is employed, and the starting tree is checked for compatibility with fossil ages.
=> Fix issue #354 once again

help/md/mcmc.md
This PR adds details about the mcmc.run method.  I couldn't find this information elsewhere in the documentation or tutorials.
I have inferred the stopping rule behaviour by experiment and by glancing at the source code.  Please confirm it's correct before pulling!
These changes might also be usefully applied to the mcmcmc manual page.
=> Detail the mcmc.run method

src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.h, src/revlanguage/distributions/phylogenetics/tree/Dist_ConstrainedTopology.cpp, src/revlanguage/distributions/phylogenetics/tree/Dist_ConstrainedTopology.h, src/revlanguage/distributions/phylogenetics/tree/Dist_ConstrainedUnrootedTopology.cpp
This PR is intended to fix issue #477, which turned out to be essentially the same as issue #354 except that it affected `dnConstrainedTopology` rather than `dnBDSTP`: supplying a user-specified initial tree overwrote the ages of fossil taxa (min = max = 0), making it impossible to sample them from the [min, max] intervals specified in a taxon info file. I have added extra code to the `TopologyConstrainedTreeDistribution` constructor that checks whether a starting tree is present and whether it contains fossils. If both of these conditions are satisfied, it runs `TreeUtilities::startingTreeInitializer()` on the initial tree to replace each of its tips with the previously specified taxon of the same name. As with `dnBDSTP`, a new `ageCheckPrecision` argument has been added to specify how …
=> Sampling fossil ages with dnConstrainedTopology + initial tree

src/CMakeLists.txt
The multiple calls seem to be unnecessary, and were a source of confusion whilst debugging; I suggest merging into with a single entry; multiple lines make it clearer what's included.
=> Single call to target_link_libraries

src/CMakeLists.txt
Big object support was necessary for me to build RevBayes.
The MSVC option is potentially unnecessary – I didn't end up getting RevBayes to build under msvc.
=> Big object support

.gitignore
https://revbayes.github.io/developer/setup/ tells the user to add `build/` to `.gitignore`; but as the repo does not contain any tracked files in the `build/` directory, it's not clear why `build/` shouldn't just be included in the default `.gitignore` file.
This would also simplify the process of switching between branches using Git.
=> Add `build/` to .gitignore

projects/cmake/regenerate.sh
Another instance of the typo addressed in #491 – this time causing boost libraries not to be included via `generated_include_dirs.cmake`
=> Boost_INCLUDE_DIR*S*

src/revlanguage/functions/basic/Func_type.cpp
This adds an extra argument `verbose` that defaults to `FALSE`.  When `verbose=True` is specified, it shows the full typespec and not just the last element:
``` R
> type(0.5)
Probability
> type(0.5,TRUE)
Probability, RealPos, Real, RevObject
```
=> Modify `type( )` so that you can see the full type-spec

src/core/utils/RbFileManager.cpp, src/core/utils/RbFileManager.h, src/revlanguage/functions/io/Func_source.cpp
We can simply read the whole file into a string and execute the string.  That way the execution sees the way the file looked when we ran the source command.
=> Avoid crashing if a file changes while we are source( )-ing it.

src/core/distributions/MixtureDistribution.h
The initial value of MixtureDistribution objects wasn't getting set correctly.
=> Fix mixture distribution.

src/revlanguage/datatypes/basic/Integer.cpp, src/revlanguage/datatypes/basic/IntegerPos.h, src/revlanguage/datatypes/basic/Natural.h, src/revlanguage/datatypes/basic/Real.cpp, src/revlanguage/datatypes/basic/RealPos.h
As noted in issue #99 there is a debate as to whether RealPos should be >=0 or >0 and right now the constructors assume the first and the conversions the second
I don't have a strong opinion either way but it should at least be coherent, so this PR aligns all behaviour to >=0 and documents it
Also fixes `sqrt` bug from #99
=> Making RealPos type coherent between conversion and construction

src/core/io/MatrixReader.cpp
Simple fix for `readMatrix()`; should be self-explanatory.
=> Allow reading non-square matrices

help/md/time.md
`time("fromBeginning")` counts milliseconds since 1400-Jan-01, not 1970-Jan-01.
=> Another `time()` doc fix

src/core/analysis/mcmc/Mcmc.cpp, src/core/help/RbHelpDatabase.cpp, src/core/moves/MetropolisHastingsMove.cpp, src/core/moves/SliceSamplingMove.cpp, src/core/moves/proposal/Proposal.cpp, src/core/moves/proposal/Proposal.h, src/core/utils/RbSettings.cpp, src/core/utils/RbSettings.h, src/revlanguage/functions/io/Func_source.cpp
This change makes `--setOption debugMCMC=1` actually work for Metropolis-Hastings moves.  Previously some of the code to check the node PDFs was actually hiding the recalculation bugs by doing extra recalculation, but only during debugging!
This change also separates logging from debugging.  The logging option is `logMCMC`.  For Metropolis-Hastings moves and the values are:
- `1`  writes out the generation, step within each generation, and move name for each move.
- `2` also writes out posterior, likelihood, prior, and Hastings ratios.
- `3` writes out each changed PDF along with its node name.
Together, these should allow debugging #565 and #567.
=> Debug mcmc

src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.h, src/core/distributions/phylogenetics/tree/birthdeath/EpisodicBirthDeathProcess.h, src/core/distributions/phylogenetics/tree/birthdeath/FossilizedBirthDeathSpeciationProcess.h, src/revlanguage/distributions/phylogenetics/tree/Dist_FBDP.h
Flagged with a warning on xcode 15 – and worth fixing I think; I've found explicit override marking helpful recently.
=> Mark overridden functions

src/revlanguage/datatypes/AbstractModelObject.h, src/revlanguage/datatypes/ModelObject.h, src/revlanguage/datatypes/RevObject.cpp, src/revlanguage/datatypes/RevObject.h, src/revlanguage/functions/MemberProcedure.cpp, src/revlanguage/functions/argumentrules/ArgumentRule.cpp, src/revlanguage/workspace/FunctionTable.cpp, src/revlanguage/workspace/FunctionTable.h, src/revlanguage/workspace/MethodTable.cpp
Revbayes throw a lot of exceptions that are immediately caught and ignored.  This PR removes some of these exceptions.  The main benefits are:
1. should be faster
2. it is possible to do `catch throw` in gdb and find where an error comes from.
=> Remove useless exceptions

src/core/distributions/phylogenetics/tree/AbstractRootedTreeDistribution.cpp, src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp, src/core/utils/RbSettings.cpp, src/core/utils/RbSettings.h
This PR allows logging a reason why we return -Inf.
```
if( the_node.getAge() - the_node.getParent().getAge() > 0 )
{
return withReason(Double::neginf)<<"Pr(tree)=0: node age "<<the_node.getAge()<<" greater than parent age "<<the_node.getParent().getAge();
}
```
The reason is only logged if `logMCMC >= 2`.
Issues:
- should we use a separate option?  Or `logMCMC >= 1`?
Changes:
- The message no longer needs to specify "\n".
=> Log reason for -Inf and NaN

src/core/analysis/mcmc/Mcmc.cpp, src/core/dag/StochasticNode.h, src/core/moves/MetropolisHastingsMove.cpp, src/revlanguage/dag/RlContinuousStochasticNode.cpp, src/revlanguage/dag/RlStochasticNode.h
This PR does four things:
1. Combine lnProb and needs_probability_recalculation into an `optional<double>`.  This prevents accessing `lnProb` when its value is invalid.
2. Change `stored_ln_prob` into an `optional<optional<double>>`.  This outer optional explicitly tracks whether there current is a previous probability or not.  The inner optional tracks whether the previous probability is invalid or not, like `lnProb`.
3. Fixes the check for different log likelihoods to catch cases like `-10 -> -Inf`, which we mistakenly did not catch before.
4. Check that final PDFs are the same as initial PDFs if the move is rejected.
=> Improve MCMC checks

src/core/datatypes/phylogenetics/characterdata/ContinuousTaxonData.cpp
In the spirit of cleaning up the code base and getting rid of compiler warnings (see e.g. #589), here's another small change to prevent Xcode from screaming at me...
=> Get rid of `sprintf` in favor of `snprintf`

src/core/functions/phylogenetics/TreeAssemblyFunction.cpp
This PR makes it simpler to debug a mismatch between the number of branches and the number of branch lengths by including each value in the text of the error message.
=> Report values in error message

.github/workflows/build.yml
The macOS ARM tests were failing because we manually installed `pkg-config`, but `meson` now seems to depend on an alternative implementation called `pkgconf` that provides the same links.
Just stop manually installing `pkg-config` and let meson handle its own dependencies.
=> Try unbreaking macOS ARM tests.

src/core/dag/DagNode.cpp, src/core/dag/DagNode.h, src/core/dag/StochasticNode.h, src/core/moves/MetropolisHastingsMove.cpp, tests/run_integration_tests.sh
Previously we always rejected any move where a stochastic node probability changed from zero or NaN to something finite.  But such moves should be fine.  This might possibly allow MCMC to solve some constraints by wandering around until PDFs that are 0 change to something non-zero.
=> Don't reject Metropolis-Hastings proposals because one PDF changes from NaN or Zero to something positive and finite.

tests/test_basics/output_expected/ignore.errout, tests/test_basics/scripts/ignore.Rev
Add ignore.errout test output.
Adding a test to check that we get the right errors would indeed be useful.  Right now I have some commented-out lines in the test that could be added in to check errors.  However, it seems that RevBayes quits running the script at the first error which means that you can't test multiple errors per script.  I plan to address this after 1.2.5 as part of changing the options to match Rscript.
=> Add stdout/stderr test.

src/revlanguage/utils/RbVersion.cpp
Oops -- I apparently changed the version number only in `meson.build`, but it also has to be changed in `revlanguage/utils/RbVersion.cpp'.
=> Fix version number for 1.2.5

src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h
There seems to be a small problem if you have a data matrix that looks something like this
```  
MATRIX                                  [HCP]
balaenoptera_borealis                010
balaenoptera_edeni                   010
balaenoptera_musculus                011
balaenoptera_physalus                010
balantiopteryx_infusca               011
balantiopteryx_io                    011
balantiopteryx_plicata               011
bandicota_savilei                    000
barbastella_barbastellus             011
barbastella_leucomelas               011
bassaricyon_gabbii                   000
bassariscus_sumichrasti              000
bathyergus_janetta                   101
batomys_granti                       100
batomys_salomonseni                  100
bdeogale_crassicauda                 010 …
```
=> simmap bugfix for when some characters are excluded

NEWS.md, meson.build, src/revlanguage/utils/RbVersion.cpp
Bump version to v1.2.6-preview after v1.2.5 release.
=> Bump version after v1.2.5 release

src/core/analysis/mcmc/Mcmcmc.cpp, src/core/analysis/mcmc/Mcmcmc.h
This should fix #651.
It'd be great to add a test for this, but the analysis where this issue popped up keeps crashing even after it is fixed – now for a different reason that no longer has to do with MC^3.
=> Prevent loss of integer precision in MC^3

meson.build, src/core/functions/phylogenetics/CheckNodeOrderConstraintsFunction.cpp, src/core/functions/phylogenetics/CheckNodeOrderConstraintsFunction.h, src/core/functions/phylogenetics/ComputeWeightedNodeOrderConstraintsScoreFunction.cpp, src/core/functions/phylogenetics/ComputeWeightedNodeOrderConstraintsScoreFunction.h, src/core/functions/phylogenetics/DispersalExtinctionRateStructureFunction.cpp, src/core/functions/phylogenetics/DispersalExtinctionRateStructureFunction.h, src/core/functions/phylogenetics/DispersalExtinctionRootStructureFunction.cpp, src/core/functions/phylogenetics/DispersalExtinctionRootStructureFunction.h, src/core/functions/phylogenetics/StitchTreeFunction.cpp, src/core/functions/phylogenetics/StitchTreeFunction.h, src/core/functions/phylogenetics/TreeScaleFunction.cpp, src/core/functions/phylogenetics/TreeScaleFunction.h, src/core/functions/phylogenetics/tree/ExtantTreeFunction.cpp, src/core/functions/phylogenetics/tree/ExtantTreeFunction.h
Very few functions specialize touch( ), keep( ), and restore( ).
These functions do specialize them, but then just call the parent class function which (a) would happen anyway without the specialization and (b) also doesn't do anything.
Let's remove these specializations so that its clear which few functions actually specialize touch/keep/restore.
I have also tacked on an unrelated change that fixes the name of rb-help2yml for the meson build.
=> Remove empty touch( ), keep( ), and  restore( ) specializations.

src/core/analysis/MonteCarloAnalysis.cpp
This is an attempt to fix issue #428 by explicitly setting seeds instead of doing draws
I have tested it with the issue script and I obtain 10 separate log files with no identical output
=> Use different seeds for replicates in MPI run

help/md/mvDPPValueBetaSimplex.md, help/md/mvDPPValueScaling.md, help/md/mvDPPValueSliding.md, src/core/help/RbHelpDatabase.cpp, src/revlanguage/workspace/RbRegister_Move.cpp
At my request, PR #606 deleted the Markdown help file for `mvDPPValueBetaSimplex`, because neither @ms609 nor myself could find the source code for it. The help file was empty, so no great harm was caused by this, but the move does in fact exist. The reason why we couldn't find any occurrence of the string "DPPValueBetaSimplex" in the `src` directory is that it is derived from a template (`DPPTableValueUpdate.h`). This PR (1) adds a brief note to the move register to clarify this, and (2) provides help files for all three moves deriving from `DPPTableValueUpdate` (`mvDPPValueBetaSimplex`, `mvDPPValueScaling`, `mvDPPValueSliding`).
=> Document DPP moves

src/core/analysis/mcmc/Mcmc.cpp, src/core/analysis/mcmc/Mcmcmc.cpp
This PR makes the following changes to `Mcmcmc.cpp`:
1. Addresses @bredelings's comment under PR #652 (which was probably merged prematurely) and avoids subtraction in a `for`-loop that checks if `ht[i+1]` is valid;
2. Solves issue #651 (and partially #609), which ultimately stems from the fact that the interpolation system we are using to correct lower-than-allowed chain heats can, under certain circumstances, produce `nan` values, which then screw up everything else.
It's still not clear to me why the problem with `nan` heats only appeared on certain platforms, but I am confident that the interpolation system now does what the corresponding source code comment says it should do. I have verified that this PR solves the issue on macOS(ARM64) 15.3 with clang 16 (where it was previously …
=> Prevent NaN heats in MC^3

tests/run_integration_tests.sh
Changed `tests/run_integration_tests.sh` to make tutorial tests more flexible. Originally, one had to write a `test.sh` script for each tutorial (and there were scripts written for the fbd, dating, and ctmc tutorial only), which only allowed for one script per test as it was written. To make this more flexible, we changed the integration tests script so that it runs each script in a file `tests.txt` in a tutorial directory. In this way, we can ensure tutorial developers can specify which scripts must be tested, so that scripts that should not be run (e.g. when they are just written to set up variables for a master script) will not be accidentally added to the tests. To test this, I also reviewed the fbd, dating and ctmc tutorials to make sure the html and scripts matched, deleted …
=> Revamped tutorial testing

tests/run_integration_tests.sh
Minor change to `tests/run_integration_tests.sh` to ensure that tutorial tests using checkpointing (e.g. `ctmc`) can be run without a hitch. It simply changes the `checkpointInterval` argument (if there is one) to 1 in the copy script used for the test run. Also updated git submodule.
=> Ensuring integration tests can run tutorial checkpoint tests

src/core/datatypes/phylogenetics/character/DiscreteCharacterState.cpp, src/core/datatypes/phylogenetics/character/DiscreteCharacterState.h, src/core/datatypes/phylogenetics/character/StandardState.cpp, src/core/datatypes/phylogenetics/character/StandardState.h, src/core/datatypes/phylogenetics/characterdata/AbstractCharacterData.cpp, src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractHomologousDiscreteCharacterData.cpp
This should be resetting state labels when setting partition by state size. Thus, it fixes the issue that the state space still looks larger.
=> Fix state space when subsetting by state space

src/core/analysis/mcmc/Mcmc.cpp
It looks like current practice is to call `monitors[i].openStream()` on the monitors for every chain -- including hot chains.  However, we only call `monitors[i].closeStream()` on the monitors for the active chain.
Currently all chains in an Mcmcmc analysis have their own duplicate version of each monitor.  For an analysis with 4 chains, we thus open the log file 4 times. The log file is open from 4 different fstream objects, and we write to the file sometimes through one fstream object, and sometimes through another object, as different chains become active.  The fact that this works at all boggles the mind.  Perhaps this explains why we seek to the end of the file before writing?
But apparently it seems to work.  However, after we stop the MCMCMC and restart it, writing to the file …
=> Fix logging when running Mcmcmc twice.

.github/workflows/release.yml, NEWS.md, meson.build, src/revlanguage/utils/RbVersion.cpp
Here's a PR to bump the version numbers.
Before release, we need to:
- check that the release scripts work by making a tag like `test-3.0` and pushing it, and checking github actions jobs successfully generate the release artifacts.  Its possible to delete the tag afterwards.
- the NEWS file just contains the list of PRs and new contributors.  We need to summarize and organize this so that its helpful to end users.  Many PRs have a description that is understandable only to developers. Sometimes multiple PRs are needed to fix the same issue, and they should be combined.  And somethings are invisible to end users and should probably not be listed.  Probably we can put documentation PRs in their own category.
=> Bump version to v1.3.0 and add list of PRs as release notes.

.github/workflows/release.yml, meson.build, src/CMakeLists.txt, src/core/analysis/PowerPosteriorAnalysis.cpp, src/core/io/NclReader.cpp, src/core/utils/RbFileManager.cpp, src/core/utils/RbFileManager.h, src/core/utils/RbSettings.cpp, src/libs/tensorphylo/Loader.cpp, src/libs/tensorphylo/Loader.h, src/revlanguage/functions/basic/Func_getwd.cpp, src/revlanguage/functions/basic/Func_setwd.cpp, src/revlanguage/functions/io/Func_source.cpp, src/revlanguage/ui/RevClient.cpp
We can now use `std::filesystem` in place of `boost::filesystem`, dropping a link-time dependency on one boost library.
=> Remove boost filesystem
